apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: plugins
  name: plugins
  namespace: etherpad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
